#!/usr/bin/env bash


if test ! -f venv/touchfile; then
  # Setup the virtual environment
  test -d venv || virtualenv venv
  source venv/bin/activate
  # Install waterline from main
  pip install git+https://github.com/nickwanninger/waterline/archive/main.zip
  touch venv/touchfile
else
  source venv/bin/activate
fi


python3 $@
